Feat/special score
TFcis/NTOJ pull request #98
Opened 2024-10-18 06:29 UTC by tobiichi3227

In this PR, we implemented support for the special scores.
The details of the special score were written in the [TFcisWiki](https://wiki.tfcis.org/TOJ#Special_Score_&_Status).
We also fixed an emergency that caused a race condition in judge dispatching, which was reported by @blameazu.

Here are some minor changes included in this PR
- Pro-rank are also ranked by score and a score column has been added
- Add a new status: SJE(Special Judge Error) to help admin better identify errors
- Add a warning label on the problem update page to inform admin that only problem-package(.tar.xz) can be uploaded
- Enhance robustness in parsing problem package config
- Clean up unused code in [services/pro.py](https://github.com/TFcis/NTOJ/compare/v2.0...tobiichi3227:NTOJ:feat/special-score?expand=1#diff-3dc5d01520df9a75017c17170c62ec5cbac1fedfa4ff3f297ccb09a3c4585094L306)

2024-10-21 15:01 UTC, LifeAdventurer requested changes

2024-10-21 15:01 UTC, lifeadventurer commented on src/services/judge.py
> +                        except decimal.DecimalException:
You could improve the `try-except` block by specifically catching `InvalidOperation`, which is the more precise exception for decimal conversion issues instead of the general `DecimalException`.

2024-10-21 15:01 UTC, lifeadventurer commented on src/tests/e2e/contest.py
In this file, the repetition of `await self.upload_problem` and the similar structure of the POST requests could be greatly simplified using a loop.

2024-10-21 15:01 UTC, lifeadventurer commented on src/tests/e2e/manage/pro/specialscore.py
In this file, the testing of problem submissions for different scoring styles (`cf_style_special_score` and `cms_style_special_score`) has repetitive patterns in both sections, especially when handling requests and assertions.

Refactor Suggestion:
- Loop through test cases: When submitting problems and checking results, you could use loops to reduce redundancy, especially for similar submissions.
- Reuse functions: Break down repetitive parts like POST requests and file uploads into reusable functions.

2024-10-21 15:02 UTC, LifeAdventurer commented
In conclusion, you've done a great job with the pull request description! It's clear, detailed, and well-structured, making it much easier to understand the context and changes. Keep up the good work!

2024-10-23 12:08 UTC, LifeAdventurer reviewed
Consider changing the URL to which the test sends requests to a constant.

2024-10-23 12:24 UTC, tobiichi3227 commented
ok

2024-10-23 13:35 UTC, tobiichi3227 commented
@LifeAdventurer

2024-10-24 08:59 UTC, LifeAdventurer approved these changes

2024-10-24 09:07 UTC, merged